# Generated by Django 5.1.6 on 2025-02-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='profiles/default.png', help_text='Upload a profile photo (max 2MB, 1000x1000px)', null=True, upload_to='profiles/', verbose_name='Profile Photo'),
        ),
    ]
