# Generated by Django 5.1.6 on 2025-02-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_uploaded_at_alter_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uploaded_at',
            new_name='updated_at',
        ),
    ]
