# Generated by Django 5.1.6 on 2025-02-25 18:21

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_set_like_last', to='chat.message'),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True),
        ),
    ]
