# Generated by Django 5.1.6 on 2025-02-26 12:58

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('sent', 'Sent')], default='sent', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True),
        ),
    ]
