# Generated by Django 5.1.6 on 2025-02-26 15:23

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_message_status_message_read_alter_room_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(default=shortuuid.main.ShortUUID.uuid, editable=False, unique=True),
        ),
    ]
